### ISSUE TITLE
Make this a PR?

### ISSUE THREAD

**Issue by mallorbc** [JonathanFly/bark#1]
You make this a PR

**Comment by JonathanFly** [comment]
I'll try to find time this weekend. I have a personal Bark fork that has been completely ripped apart, I might try and port some features over in a clean way so they can theoretically merge with main. (I've been monkeying with the sampling to see what happens, and it's gotten out of control.)

**Comment by mallorbc** [comment]
If are too busy, I can do it.  I just think the cli you made is great and would be good to add.

**Comment by 0xharib** [comment]
I am trying to understand how to use this non-cli in an ipynb - would it be possible to put something together here? Thanks!

**Comment by WordpressReady** [comment]
> I am trying to understand how to use this non-cli in an ipynb - would it be possible to put something together here? Thanks!

I found this , https://rafat-joy99.medium.com/how-to-run-py-files-on-google-colab-46af2831e166
 then uploaded the project to Google Drive and used something similar to:
!python /content/drive/MyDrive/bark-main/bark_perform.py (parameters here)
That worked

**Comment by JonathanFly** [comment]
The reason why I'm late updating is that it rearranged the code so it's not all on the CLI, which means it's now very easy to make a Colab of Notebook with it. So soon!

**Comment by JonathanFly** [comment]
I'm closing this for now, but on my list is to make a cleaner version of this fork works just as a standalone file in the suno-ai unmodified bark repo. And you you you should be able to make a Notebook easy now, look at the Grado example.
