### ISSUE TITLE
Source code of script

### ISSUE THREAD

**Issue by DblK** [JonathanFly/bark#104]
Hi,

I tried to find the script in the release ZIP but could not find them.
I was hoping to make few changes inside.

Could you provide those script as well and maybe a Github Action to create the release automatically.
It will saves some time for you.

Thx

**Comment by JonathanFly** [comment]
It's in the released section: https://github.com/JonathanFly/bark/releases

It's also here, but should be the same code: https://github.com/JonathanFly/bark-installer
