### ISSUE TITLE
Installation error occurred, seems to still be a path issue with conda.

### ISSUE THREAD

**Issue by alex9441** [JonathanFly/bark#110]
Run INSTALL_BARK_INFINITY.bat.
Received errors as follows：

ERROR:root:Command '"C:\00000_suno_ai\bark\installer_files\conda\condabin\conda.bat" activate "C:\00000_suno_ai\bark\installer_files\env" >nul && ffdl install -U --add-path 6.0@full' failed with exit status code '1'. Exiting...
If there is an error, take note of it here.

Run START_BARK_INFINITY.bat
Received errors as follows：

Running command: "C:\00000_suno_ai\bark\installer_files\conda\condabin\conda.bat" activate "C:\00000_suno_ai\bark\installer_files\env" >nul && conda
Running command: "C:\00000_suno_ai\bark\installer_files\conda\condabin\conda.bat" activate "C:\00000_suno_ai\bark\installer_files\env" >nul && python bark_webui.py
python: can't open file 'C:\\00000_suno_ai\\bark\\bark\\bark_webui.py': [Errno 2] No such file or directory
If there is an error, take note of it here.

**Comment by JonathanFly** [comment]
If you downloaded the zip less than 3 hours ago, can you try again with a fresh downloaded .zip file? It looks like it didn't install at all, even to the point of downloading bark_webui.py.

**Comment by alex9441** [comment]
Okay, the problem is resolved. It was because of my antivirus software that blocked the installation program.

**Comment by JonathanFly** [comment]
Great, thanks for following up.
