### ISSUE TITLE
Cloning own voice

### ISSUE THREAD

**Issue by ZmiennyVT** [JonathanFly/bark#13]
Could someone describe to me how to clone my own voice? 
I see .wav and .npz files here but Is there any way to add my own voice?

**Comment by ksylvan** [comment]
I'd love to know this too.

**Comment by JonathanFly** [comment]
I'll try to sneak this in my weekend update, but I may delay it just to get at new stable version with Notebook and Gradio out.

**Comment by ksylvan** [comment]
Thanks, @JonathanFly

**Comment by HobisPL** [comment]
> I'll try to sneak this in my weekend update, but I may delay it just to get at new stable version with Notebook and Gradio out.

I understand that you are referring to cloning using WAV and NPZ. Unfortunately, this method works very poorly, or I would even say that it does not work at all. There is a link provided on the official repository, maybe it can be somehow connected to train your own voices.

https://github.com/suno-ai/bark/issues/37

**Comment by JonathanFly** [comment]
It doesn't seem very effective, I integrated what cloning was there. 

![image](https://user-images.githubusercontent.com/163408/236074860-4ff0f05b-d94d-4bef-9795-516f3b58db3e.png)
