### ISSUE TITLE
I can't get it to run on the GPU

### ISSUE THREAD

**Issue by El-Hondo** [JonathanFly/bark#14]
This is what I get. 

`Loading Bark models...
No GPU being used. Careful, Inference might be extremely slow!` 
I have a 2080 TI and it works with with SD and GPTs.

Any ideas?

**Comment by merecesarchviz** [comment]
I have the same problem and i have a rtx 4090! how we can set it to run with GPU?

**Comment by merecesarchviz** [comment]
I found the solution is because the torch version! so you have to install: pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

**Comment by El-Hondo** [comment]
> I found the solution is because the torch version! so you have to install: pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

I think it is not the solution for me. It says the requirements are already satisfied.  :(

**Comment by Apyr101** [comment]
> > I found the solution is because the torch version! so you have to install: pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
> 
> I think it is not the solution for me. It says the requirements are already satisfied. :(

Reinstalling torch worked for me 
pip uninstall torch 
and then 
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

**Comment by El-Hondo** [comment]
> > > I found the solution is because the torch version! so you have to install: pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
> > 
> > 
> > I think it is not the solution for me. It says the requirements are already satisfied. :(
> 
> Reinstalling torch worked for me pip uninstall torch and then pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

That worked. Thank you!

**Comment by merecesarchviz** [comment]
> > > > I found the solution is because the torch version! so you have to install: pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
> > > 
> > > 
> > > I think it is not the solution for me. It says the requirements are already satisfied. :(
> > 
> > 
> > Reinstalling torch worked for me pip uninstall torch and then pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
> 
> That worked. Thank you!

I had the same problem you need first to go the and delete manually the folders "Torch" , "Tourchaudio", "Torchvision" that are located: c:\users\XXXXXX\appdata\local\programs\python\python310\lib\site-packages

then install it with the cmd command: pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

**Comment by JonathanFly** [comment]
Hopefully it's all working now, and there are new instructions, and (maybe) a full installer coming...
