### ISSUE TITLE
"The requested array has an inhomogeneous shape after 1 dimensions"

### ISSUE THREAD

**Issue by jurandfantom** [JonathanFly/bark#19]
Windows 10, RTX 4090

1) Git cloned repo
2) missing encodec - instal it via "pip install -U encodec"
3) missing funcy - instal it via "pip install -U funcy"
4) missing scipy - instal it via "pip install -U scipy"
5) as following

E:\Magazyn\Grafika\AI\Text2Voice\bark>python bark_speak.py --text_prompt "It is a mistake to think you can solve any major problems just with potatoes." --history_prompt en_speaker_3
Loading Bark models...
Models loaded.
Estimated time: 6.00 seconds.
Generating: It is a mistake to think you can solve any major problems just with potatoes.
Using speaker: en_speaker_3
history_prompt in gen: en_speaker_3
en_speaker_3
aa
100%|████████████████████████████████████████████████████████████████████████████████| 100/100 [00:12<00:00,  8.20it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 31/31 [00:35<00:00,  1.15s/it]
Traceback (most recent call last):
  File "E:\Magazyn\Grafika\AI\Text2Voice\bark\bark_speak.py", line 175, in <module>
    main(args)
  File "E:\Magazyn\Grafika\AI\Text2Voice\bark\bark_speak.py", line 157, in main
    gen_and_save_audio(prompt, history_prompt, text_temp, waveform_temp, filename, output_dir)
  File "E:\Magazyn\Grafika\AI\Text2Voice\bark\bark_speak.py", line 97, in gen_and_save_audio
    save_audio_to_file(filename, audio_array, SAMPLE_RATE, output_dir=output_dir)
  File "E:\Magazyn\Grafika\AI\Text2Voice\bark\bark_speak.py", line 63, in save_audio_to_file
    sf.write(filepath, audio_array, sample_rate, format=format, subtype=subtype)
  File "C:\Users\jurandfantom\miniconda3\lib\site-packages\soundfile.py", line 338, in write
    data = np.asarray(data)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

E:\Magazyn\Grafika\AI\Text2Voice\bark>

**Comment by micky-meecky** [comment]
> Windows 10, RTX 4090
> 
> 1. Git cloned repo
> 2. missing encodec - instal it via "pip install -U encodec"
> 3. missing funcy - instal it via "pip install -U funcy"
> 4. missing scipy - instal it via "pip install -U scipy"
> 5. as following
> 
> E:\Magazyn\Grafika\AI\Text2Voice\bark>python bark_speak.py --text_prompt "It is a mistake to think you can solve any major problems just with potatoes." --history_prompt en_speaker_3 Loading Bark models... Models loaded. Estimated time: 6.00 seconds. Generating: It is a mistake to think you can solve any major problems just with potatoes. Using speaker: en_speaker_3 history_prompt in gen: en_speaker_3 en_speaker_3 aa 100%|████████████████████████████████████████████████████████████████████████████████| 100/100 [00:12<00:00, 8.20it/s] 100%|██████████████████████████████████████████████████████████████████████████████████| 31/31 [00:35<00:00, 1.15s/it] Traceback (most recent call last): File "E:\Magazyn\Grafika\AI\Text2Voice\bark\bark_speak.py", line 175, in main(args) File "E:\Magazyn\Grafika\AI\Text2Voice\bark\bark_speak.py", line 157, in main gen_and_save_audio(prompt, history_prompt, text_temp, waveform_temp, filename, output_dir) File "E:\Magazyn\Grafika\AI\Text2Voice\bark\bark_speak.py", line 97, in gen_and_save_audio save_audio_to_file(filename, audio_array, SAMPLE_RATE, output_dir=output_dir) File "E:\Magazyn\Grafika\AI\Text2Voice\bark\bark_speak.py", line 63, in save_audio_to_file sf.write(filepath, audio_array, sample_rate, format=format, subtype=subtype) File "C:\Users\jurandfantom\miniconda3\lib\site-packages\soundfile.py", line 338, in write data = np.asarray(data) ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.
> 
> E:\Magazyn\Grafika\AI\Text2Voice\bark>

"I debugged it and found out that the issue was with the audio_array. Originally, it did not have x_coarse_gen and x_fine_gen, but he added them which caused a dimension error in the ndarray. After modifying it and passing the data of the first dimension, it worked."

    save_audio_to_file(filename, audio_array[0], SAMPLE_RATE, output_dir=output_dir)

**Comment by JonathanFly** [comment]
This was a problem where it expected multiple audio segments in audio_array (for longer clips). All fixed now.
