### ISSUE TITLE
Is there a way to do line breaks like with the GUI?

### ISSUE THREAD

**Issue by senornz** [JonathanFly/bark#20]
It seems that line breaks might help with song/rap structure -or it may have no effect, is very hard to tell!  

Anyway, is there a way to do that with command line prompt?

(This is a great project, thank you so much!)

**Comment by JonathanFly** [comment]
> It seems that line breaks might help with song/rap structure -or it may have no effect, is very hard to tell!
> 
> Anyway, is there a way to do that with command line prompt?
> 
> (This is a great project, thank you so much!)

You can also use a text or edit bark_perform.py. Or use the NEW BARK INFINITY GUI!
