### ISSUE TITLE
Low VRAM or CUDA out of memory for BARK INFINITY Solved

### ISSUE THREAD

**Issue by huzidev** [JonathanFly/bark#23]
python bark_perform.py --use_smaller_models --text_prompt "Hello, world testing this for Bark Infinity since it's giving CUDA out of memory error so to overcome this error just simply use --use_smaller_models as args" --split_by_words 35

in web-ui version of bark and in suno-ai/bark we can do ["SUNO_USE_SMALL_MODELS"] = "True" but can't in this Infinity so to overcome this CUDA out of memory error simply use --use_smaller_models as args in cmd

**Comment by wuliwuliL** [comment]
Same issue, it always show me
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory every time I try to use smaller model

**Comment by huzidev** [comment]
> Same issue, it always show me RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory every time I try to use smaller model

This is not V-Ram error seems something is wrong with yours torch version

Maybe this will fix yours error
- pip3 uninstall torch
- pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
- after this restart yours system 
- then check it'll surely fix if this error is related to torch or pytorch
