### ISSUE TITLE
How to use GPU using bark?

### ISSUE THREAD

**Issue by Boeing1337** [JonathanFly/bark#27]
Hello there, so the question is "How to use GPU using bark"?

**Comment by Starfire70** [comment]
Answered in a previous issue (worked for me):

Reinstalling torch worked for me
pip uninstall torch
and then
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

**Comment by JonathanFly** [comment]
There's some new instructions on the README, try the "Mamba/Conda Install" it's step by step exactly.
