### ISSUE TITLE
new API interfaces for the new methods

### ISSUE THREAD

**Issue by bghira** [JonathanFly/bark#31]
As an integrator, I would like to have access to the same logic being used by the `bark_perform.py` script via `bark.api`.

Please relocate these methods to the api and instead, import and use them through the perform script.

Additionally, the methods you have updated in the api have not had their doc strings updated correctly, so it confusingly returns a `tuple` now instead of the audio array.

**Comment by JonathanFly** [comment]
> As an integrator, I would like to have access to the same logic being used by the `bark_perform.py` script via `bark.api`.
> 
> Please relocate these methods to the api and instead, import and use them through the perform script.
> 

All set. I think generate_audio has the same returns as base bark, though api functions I added may not. Also see the Colab linked in the README.
