### ISSUE TITLE
made batch file for autorun and probably an issue with --history_prompt

### ISSUE THREAD

**Issue by Eldiablozzz** [JonathanFly/bark#32]
I made a quick batch file to run the script with args. On weekend i will make GUI with tkinter so that anyone can copy paste their prompt and run program with their selected speaker and selected settings. If anyone wants to take over i will provide the files i have made. 

And many thanks to OP for making such awesome AI work with larger text.

BTW: i noticed one thing, when it splits text the first one gives --history_prompt in gen: chosen speaker but on next generations it gives --history_prompt in gen: none. could that be fixed?

**Comment by JonathanFly** [comment]
I changed so much I probably fixed this bug? (If you didn't notice, update, lots of cool stuff.)
