### ISSUE TITLE
where is Ramshackle Gradio App and dev branch?

### ISSUE THREAD

**Issue by FurkanGozukara** [JonathanFly/bark#33]
I want to generate long consistent and natural audio for my youtube videos to make a voice over : https://www.youtube.com/SECourses

I tried tortoise TTS even cloned a voice but natural and high quality enough

I need consistency and high quality

Reading the repo it says Ramshackle Gradio App

But can't find this dev branch or anything

I can be volunteer to test and make a tutorial video

my discord : MonsterMMORPG#2198

**Comment by JonathanFly** [comment]
Tuesday night for testing, hopefully Wednesday public.

**Comment by FurkanGozukara** [comment]
> Tuesday night for testing, hopefully Wednesday public.

Thank you looking forward too

**Comment by JonathanFly** [comment]
\Something went wrong the one click installer, but there is some conda/mamba instructions.

**Comment by JonathanFly** [comment]
I'll still try to get the one-click out but at least it's EASIER to install now.
