### ISSUE TITLE
Long text file change voices in the middle

### ISSUE THREAD

**Issue by ShmuelRonen** [JonathanFly/bark#37]
I try the new version. thare is no option of  --stable-voice in the commands...
Even though I selected en_speaker_1 the voices changed in the middle of the process. Can this be fixed? Sending the file.

https://user-images.githubusercontent.com/80190186/235979462-749c9fc1-0dca-4f01-8108-48603a773eed.mp4

**Comment by JonathanFly** [comment]
Sorry about that, changed the name to 
```
stable_mode_interval 1
```

0 is not stable. 2,3,4 are a little stable, reset every few chunks.
