### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode characters in position 122-241:

### ISSUE THREAD

**Issue by rmcc3** [JonathanFly/bark#38]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 122-241: character maps to <undefined>
*** You may need to add PYTHONIOENCODING=utf-8 to your environment ***

This error seems to randomly appear and does not go away. No idea what causes it. Sometimes the prompts work, and other times the same prompt triggers that error, and just continues to get worse after it starts.

**Comment by JonathanFly** [comment]
Ugh. I'm on it.

**Comment by JonathanFly** [comment]
I believe it's fixed. from same place you run python bark_webui.py run `git pull`
