### ISSUE TITLE
Out of GPU VRAM luanching using python bark_perform.py command

### ISSUE THREAD

**Issue by boricuapab** [JonathanFly/bark#39]
Out of GPU VRAM luanching using python bark_perform.py command

Win10

rtx 2060 super 8gb gpu

![outOfVramOnLaunch](https://user-images.githubusercontent.com/61924816/236066905-db4f9934-9040-481c-a643-8b3b3ed7d938.PNG)

**Comment by JonathanFly** [comment]
I forget to  enable CPU offloading, just updated. Type `git pull` to get the update.t
