### ISSUE TITLE
ModuleNotFoundError: No module named 'encodec'

### ISSUE THREAD

**Issue by Crimsonfart** [JonathanFly/bark#4]
What do I have to do to make JonathanFly/bark work? I already have barkwebui inst. (oneclickinst.) and then copied the files from your repo to the bark folder and "pip install soundfile" via cmd inst.
I get the following error when i run this `python bark_speak.py --text_prompt "It is a mistake to think you can solve any major problems just with potatoes." --history_prompt en_speaker_3` command in cmd.

Microsoft Windows [Version 10.0.22621.1555]
(c) Microsoft Corporation. Alle Rechte vorbehalten.

D:\AI\Bark_WebUI\bark>python bark_speak.py --text_prompt "It is a mistake to think you can solve any major problems just with potatoes." --history_prompt en_speaker_3
Traceback (most recent call last):
  File "D:\AI\Bark_WebUI\bark\bark_speak.py", line 3, in <module>
    from bark import SAMPLE_RATE, generate_audio, preload_models
  File "D:\AI\Bark_WebUI\bark\bark\__init__.py", line 1, in <module>
    from .api import generate_audio, text_to_semantic, semantic_to_waveform
  File "D:\AI\Bark_WebUI\bark\bark\api.py", line 5, in <module>
    from .generation import codec_decode, generate_coarse, generate_fine, generate_text_semantic
  File "D:\AI\Bark_WebUI\bark\bark\generation.py", line 7, in <module>
    from encodec import EncodecModel
ModuleNotFoundError: No module named 'encodec'

D:\AI\Bark_WebUI\bark>

**Comment by JonathanFly** [comment]
Maybe the one click installer didn't work, I haven't tried it. You could "pip install -U encodec" but that should have been taken are of. Did bark work before you copied my files?

**Comment by Crimsonfart** [comment]
Thanks for the help! Yes, the webui seems to work, but I get the out of memory error message after a certain time because I only have 8 GB of VRAM.
I ran "pip install -U encodec" and it got a few things inst. Now I get a new error:

Microsoft Windows [Version 10.0.22621.1555]
(c) Microsoft Corporation. Alle Rechte vorbehalten.

D:\AI\Bark_WebUI\bark>python bark_perform.py --text_prompt "It is a mistake to think you can solve any major problems just with potatoes... or can you? (and the next page, and the next page...)" --split_by_words 35
Traceback (most recent call last):
  File "D:\AI\Bark_WebUI\bark\bark_perform.py", line 3, in <module>
    from bark import SAMPLE_RATE, generate_audio, preload_models
  File "D:\AI\Bark_WebUI\bark\bark\__init__.py", line 1, in <module>
    from .api import generate_audio, text_to_semantic, semantic_to_waveform
  File "D:\AI\Bark_WebUI\bark\bark\api.py", line 3, in <module>
    from .generation import codec_decode, generate_coarse, generate_fine, generate_text_semantic
  File "D:\AI\Bark_WebUI\bark\bark\generation.py", line 8, in <module>
    import funcy
ModuleNotFoundError: No module named 'funcy'

D:\AI\Bark_WebUI\bark>

**Comment by Crimsonfart** [comment]
i have now installed bark without oneclickinst and now it works!!! But it is extremely slow! I think it's running in CPU mode. The oneclickinstWEBUI also worked and used the GPU (GTX 3060TI) and was very fast but unfortunately I got an out of memory error at the very end. how can i start your repo in GPU mode?

**Comment by JonathanFly** [comment]
I'm out for the night, but I'll try the installer myself tomorrow. The creator is also in the Discord and I think he said was going to fork my code, but I didn't check lately.

**Comment by Crimsonfart** [comment]
[This](https://github.com/serp-ai/bark-with-voice-clone/issues/5#issuecomment-1518677400) is exactly what people with 8GB vram GPUs need, the first two models are removed from the vram after use. I tested it and it works!
