### ISSUE TITLE
Request for a version of the new model that will work as a notebook in Google Collab

### ISSUE THREAD

**Issue by ShmuelRonen** [JonathanFly/bark#42]
Thank you for youre project!!!
It is possible to make a Colab version?

**Comment by JonathanFly** [comment]
I threw together a simple example, it's in the repo or download this:

[https://raw.githubusercontent.com/JonathanFly/bark/main/notebooks/Bark_Infinity_Long_Form_Audio_Colab.ipynb](https://raw.githubusercontent.com/JonathanFly/bark/main/notebooks/Bark_Infinity_Long_Form_Audio_Colab.ipynb)

**Comment by JonathanFly** [comment]
Linked Colab from the README.
