### ISSUE TITLE
Minor bugs

### ISSUE THREAD

**Issue by Kreevoz** [JonathanFly/bark#5]
A few minor bugs, nothing game-breaking!

- When there is a `:` in the text prompt, such as "TV AD: Blah blah text here", then the script attempts to save the files with an unsanitized filename. On Windows, `:` is an illegal character in the filename, which causes no files to be saved out, only a broken 0kb file with the name up to the  `:`. Might be best to strip out everything that isn't regular text.

- When executing the same prompt twice, then any already existing speaker file will be overwritten. Only the wave file gets a _1 appended to the filename. Would be nice if this also applied to the speaker files.

**Comment by JonathanFly** [comment]
I fixed these but introduce a whole bunch more.
