### ISSUE TITLE
Using prompt_file_separator in the CLI

### ISSUE THREAD

**Issue by JDGSINC** [JonathanFly/bark#8]
Hey, I'm a bit confused on how to use the prompt_file_separator command... Would it be possible to provide a basic example on how to do so ?

**Comment by JonathanFly** [comment]
> Hey, I'm a bit confused on how to use the prompt_file_separator command... Would it be possible to provide a basic example on how to do so ?

This should probably be easier. It's like this:



```myprompts.txt 
This is the first prompt.
Lots of text here maybe. 
As long as you want.

AAAAA

This is the second prompt.

AAAAA

This is the third prompt.

AAAAA

This is the fourth prompt.
```

```
python bark_perform.py --prompt_file myprompts.txt --split_input_into_separate_prompts_by string --split_input_into_separate_prompts_by_value AAAAA 
--output_dir myprompts_samples
```
