### ISSUE TITLE
No errors, but saved mp3 is always 0 seconds long, Wav output is fine.

### ISSUE THREAD

**Issue by mediashock** [JonathanFly/bark#88]
I have 0 errors but all of the generated sounds are 0 length if I choose mp3 as file output. Wav export works fine.

=== GPU Information ===
GPU Device: NVIDIA GeForce RTX 4090
Total memory: 23.98779296875 GB
CUDA Version: 11.8
PyTorch Version: 2.0.1

OFFLOAD_CPU: True (Default is True)

**Comment by JonathanFly** [comment]
Did you use the auto installer? This is an issue with a missing library. Could be ffmpeg, could be soundfile. If you type
```ffmpeg -version``` in the same place you start Bark, does it work?

**Comment by Tomas83** [comment]
what worked?

**Comment by JonathanFly** [comment]
> what worked?

Are you having this problem?  I should be asleep but due to circumstances, I'm up for awhile right now, can sort you out. Try
A:
```
pip install ffmpeg_downloader
ffdl install -U --add-path
```
Then try typing 
```
ffmpeg -version
```
B:

```
pip uninstall soundfile
conda install pysoundfile 
```
C
```
conda uninstall pysoundfile
pip install soundfile
```

**Comment by Tomas83** [comment]
Non of this worked so I re-installed and it worked. Sorry for the late response and thanks
