### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by mtx2d** [JonathanFly/bark#9]
Thanks for making this wrapper!
Is it possible to include a requirements.txt file for this project?

**Comment by RuntimeRacer** [comment]
You can install requirements via [pyproject.toml](https://github.com/JonathanFly/bark/blob/main/pyproject.toml) by `cd`-ing into the directory and running `python -m pip install .`

**Comment by JonathanFly** [comment]
Added requirement.txt and conda .yml files
