### ISSUE TITLE
Weird error on installation

### ISSUE THREAD

**Issue by BurnedP** [JonathanFly/bark#90]
Hey, I'm trying to install through the one-click installation and I get a weird error related to the arguments passed to the conda-script. From what I can gather, it seems the libmamba solver is not loading and seems to not exist on my computer. What are some ways to resolve this?

The code I get:

usage: conda-script.py install [-h] [--revision REVISION] [-n ENVIRONMENT | -p PATH] [-c CHANNEL] [--use-local]
                               [--override-channels] [--repodata-fn REPODATA_FNS] [--strict-channel-priority]
                               [--no-channel-priority] [--no-deps | --only-deps] [--no-pin] [--copy] [--no-shortcuts]
                               [-C] [-k] [--offline] [-d] [--json] [-q] [-v] [-y] [--download-only]
                               [--show-channel-urls] [--file FILE]
                               [--solver {classic} | --experimental-solver {classic}] [--force-reinstall]
                               [--freeze-installed | --update-deps | -S | --update-all | --update-specs] [-m]
                               [--clobber] [--dev]
                               [package_spec ...]
conda-script.py install: error: argument --solver: invalid choice: 'libmamba' (choose from 'classic')
ERROR:root:Command '"C:\Tools\BarkAI\installer_files\conda\condabin\conda.bat" activate "C:\Tools\BarkAI\installer_files\env" >nul && conda install -y -k pip git --solver=libmamba' failed with exit status code '2'. Exiting...
If there is an error, take note of it here.

I'd be glad to add any more information you might consider useful :)

**Comment by JonathanFly** [comment]
Can you check if you're using the latest version of the zip file? That could also happen if you got interrupted. 

If you click the `TROUBLESHOOT_BARK_INFINITY.bat` file, then type:
```
conda install -n base -y conda-libmamba-solver
```
Then close that terminal, and run `INSTALL_BARK_INFINITY.bat` again. That might fix it.

**Comment by martsec** [comment]
I had the same error and in my case was because I had conda already installed, so some of the commands were executing the main conda instead of the one installed by bark. 

What I had to do is to change the function `install_dependencies´ of `bark_infinity_installer_webui_alternative.py`  to add the conda path. WIth this, I was able to install it no issues

```python
def install_dependencies():
    conda_path = get_conda_path()

    base_commands = [
        (f'"{conda_path}"' + " update -y -n base conda", True),
        (f'"{conda_path}"' + " install -n base -y conda-libmamba-solver", True),
        (f'"{conda_path}"' + " install -y -k pip git --solver=libmamba", True),
        (f'"{conda_path}"' + " update -y --all --solver=libmamba", True),
        ("pip install --no-input ffmpeg-downloader", True),
        ("ffdl install -U --add-path 6.0@full", True),
        ("pip install soundfile", True),
        (
            "pip install torchaudio==2.0.2+cu118 torch==2.0.1+cu118 torchvision --extra-index-url https://download.pytorch.org/whl/cu118",
            True,
        ),
        ("pip install -r requirements-allpip.txt", True),
        (
            "pip install --no-deps encodec flashy>=0.0.1 demucs audiolm_pytorch==1.1.4 fairseq@https://github.com/Sharrnah/fairseq/releases/download/v0.12.4/fairseq-0.12.4-cp310-cp310-win_amd64.whl",
            True,
        ),
    ]
    bark_commands = [
        ("git clone https://github.com/JonathanFly/bark.git", True),
    ]
    commands = base_commands if BARK_DIR.exists() else base_commands + bark_commands

    for cmd, assert_success in commands:
        run_conda_cmd(cmd, assert_success=assert_success)

    print(
        f"\n\nClose any open text terminals, and then click on the start_bark_infinity.bat file in a new window. This seems to be necessary for FFMPEG to be detected after installation.\n\nIf you have trouble, you can try TROUBLESHOOT_bark_setup_manually_by_entering_the_conda_environment.bat\n\nRemember, if you use this terminal, you will have to type 'conda deactivate' first."
    )
    run_cmd(f'"{conda_path}"' + " deactivate", assert_success=False)
```

**Comment by BurnedP** [comment]
> Can you check if you're using the latest version of the zip file? That could also happen if you got interrupted.
> 
> If you click the `TROUBLESHOOT_BARK_INFINITY.bat` file, then type:
> 
> ```
> conda install -n base -y conda-libmamba-solver
> ```
> 
> Then close that terminal, and run `INSTALL_BARK_INFINITY.bat` again. That might fix it.
> 
> If you .bat files have different names than that, you are definitely using an old version of the installer.

Yes, I'm definitely using the most recent installation files

**Comment by BurnedP** [comment]
> I had the same error and in my case was because I had conda already installed, so some of the commands were executing the main conda instead of the one installed by bark.
> 
> What I had to do is to change the function `install_dependencies` of `bark_infinity_installer_webui_alternative.py` to add the conda path. WIth this, I was able to install it no issues
> 
> ```python
> def install_dependencies():
>     conda_path = get_conda_path()
> 
>     base_commands = [
>         (f'"{conda_path}"' + " update -y -n base conda", True),
>         (f'"{conda_path}"' + " install -n base -y conda-libmamba-solver", True),
>         (f'"{conda_path}"' + " install -y -k pip git --solver=libmamba", True),
>         (f'"{conda_path}"' + " update -y --all --solver=libmamba", True),
>         ("pip install --no-input ffmpeg-downloader", True),
>         ("ffdl install -U --add-path 6.0@full", True),
>         ("pip install soundfile", True),
>         (
>             "pip install torchaudio==2.0.2+cu118 torch==2.0.1+cu118 torchvision --extra-index-url https://download.pytorch.org/whl/cu118",
>             True,
>         ),
>         ("pip install -r requirements-allpip.txt", True),
>         (
>             "pip install --no-deps encodec flashy>=0.0.1 demucs audiolm_pytorch==1.1.4 fairseq@https://github.com/Sharrnah/fairseq/releases/download/v0.12.4/fairseq-0.12.4-cp310-cp310-win_amd64.whl",
>             True,
>         ),
>     ]
>     bark_commands = [
>         ("git clone https://github.com/JonathanFly/bark.git", True),
>     ]
>     commands = base_commands if BARK_DIR.exists() else base_commands + bark_commands
> 
>     for cmd, assert_success in commands:
>         run_conda_cmd(cmd, assert_success=assert_success)
> 
>     print(
>         f"\n\nClose any open text terminals, and then click on the start_bark_infinity.bat file in a new window. This seems to be necessary for FFMPEG to be detected after installation.\n\nIf you have trouble, you can try TROUBLESHOOT_bark_setup_manually_by_entering_the_conda_environment.bat\n\nRemember, if you use this terminal, you will have to type 'conda deactivate' first."
>     )
>     run_cmd(f'"{conda_path}"' + " deactivate", assert_success=False)
> ```

This did the trick. Might be a good idea for @JonathanFly to include it on the main branch after reviewing it. Thanks for the help guys!

**Comment by JonathanFly** [comment]
I think I snuck this fix in the the last update.
